import "./styles.css";
import { ToDoList } from "./toDoCreator.js"

function screenController() {
    const listArray = [];

    const listNav = document.querySelector(".list-nav");
    const pageBody = document.querySelector(".container");

    const defaultList = new ToDoList("Default Project");
    listArray.push(defaultList);
    const defaultTaskIndex = defaultList.addToDo("Default Task", "Default Project", "This is a default task, autogenerated on page load.");


    const displayLists = () => {
        listArray.forEach(list => {
            const navListContainer = document.createElement("div");
            navListContainer.classList.add("nav-list-container");
            navListContainer.id = listArray.indexOf(list);
            listNav.appendChild(navListContainer);

            const navListUl = document.createElement("ul");
            navListContainer.appendChild(navListUl);

            const navListHeaderLi = document.createElement("li");
            navListHeaderLi.classList.add("nav-list-header");
            navListUl.appendChild(navListHeaderLi);

            const wrapperAnchor = document.createElement("a");
            wrapperAnchor.href = "#";
            wrapperAnchor.id = listArray.indexOf(list);
            navListHeaderLi.appendChild(wrapperAnchor);

            const listLogo = document.createElement("i");
            listLogo.classList.add("fa-solid");
            listLogo.classList.add("fa-hashtag");
            wrapperAnchor.appendChild(listLogo);

            const navListHeader = document.createElement("span");
            navListHeader.textContent = list.Name;
            wrapperAnchor.appendChild(navListHeader);

            wrapperAnchor.addEventListener("click", () => clickList(wrapperAnchor.id));
        });
    }

    const displayTasks = () => {

    }

    const addTask = () => {

    }

    const newList = (name) => {
        //const list =

        listArray.push(list);
        displayLists();
    }

    const deleteList = (name) => {

    }

    const clickList = (e) => {
        // Changes contents of .container to match contents of clicked Task
        pageBody.replaceChildren();
        const list = listArray[e];
        const taskArray = list.getAllToDoItems();
        taskArray.forEach(task => {
            const div = document.createElement("div");
            div.className = "task-wrapper";
            
            const title = document.createElement("h4");
            title.className = "title";
            const description = document.createElement("span");
            description.className = "description";
            const dueDate = document.createElement("span");
            dueDate.className = "dueDate";
            const priority = document.createElement("span");
            priority.className = "priority";
    
            title.textContent = task.title;
            description.textContent = task.description;

            pageBody.appendChild(div);
            div.appendChild(title);
            div.appendChild(description);
            div.appendChild(dueDate);
            div.appendChild(priority);
        });

    }

    // Test ToDo Item
    displayLists();

}



screenController();