import "./styles.css";
import { ToDoList } from "./toDoCreator.js"

function screenController() {
    const listArray = [];

    const listNav = document.querySelector(".list-nav");
    const pageBody = document.querySelector(".container");

    const defaultList = new ToDoList("Default Project");
    listArray.push(defaultList);
    const newTaskIndexOne = defaultList.addToDo("Default Task", "Default Project", "This is a default task, autogenerated on page load.");
    const newTaskIndexTwo = defaultList.addToDo("Default Task", "Default Project", "This is a default task, autogenerated on page load.");
    const newTaskIndexThree = defaultList.addToDo("Default Task", "Default Project", "This is a default task, autogenerated on page load.");
    const newTaskIndexFour = defaultList.addToDo("Default Task", "Default Project", "This is a default task, autogenerated on page load.");


    const displayLists = () => {
        listArray.forEach(list => {
            const navListContainer = document.createElement("div");
            navListContainer.classList.add("nav-list-container");
            navListContainer.id = listArray.indexOf(list);
            listNav.appendChild(navListContainer);

            const navListUl = document.createElement("ul");
            navListContainer.appendChild(navListUl);

            const navListHeaderLi = document.createElement("li");
            navListHeaderLi.classList.add("nav-list-header");
            navListUl.appendChild(navListHeaderLi);

            const div = document.createElement("div");
            div.classList.add("list-inner-flex");
            div.id = listArray.indexOf(list);
            navListHeaderLi.appendChild(div);

            const wrapperAnchor = document.createElement("a");
            wrapperAnchor.href = "#";
            wrapperAnchor.id = listArray.indexOf(list);
            div.appendChild(wrapperAnchor);

            const listLogo = document.createElement("i");
            listLogo.classList.add("fa-solid");
            listLogo.classList.add("fa-hashtag");
            wrapperAnchor.appendChild(listLogo);

            const navListHeader = document.createElement("span");
            navListHeader.textContent = list.Name;
            wrapperAnchor.appendChild(navListHeader);

            div.addEventListener("click", () => clickList(div));
        });
    }

    const displayTasks = () => {

    }

    const addTask = () => {

    }

    const newList = (name) => {
        const list = new ToDoList(name);
        listArray.push(list);
        displayLists();
    }

    const deleteList = (name) => {

    }

    const clickHome = (e) => {
        pageBody.replaceChildren();

        const divList = document.querySelectorAll("div");
        divList.forEach(element => element.classList.remove("active"));
        e.classList.add("active");


    }

    const clickToday = (e) => {
        pageBody.replaceChildren();

        const divList = document.querySelectorAll("div");
        divList.forEach(element => element.classList.remove("active"));
        e.classList.add("active");


    }

    const clickImportant = (e) => {
        pageBody.replaceChildren();

        const divList = document.querySelectorAll("div");
        divList.forEach(element => element.classList.remove("active"));
        e.classList.add("active");


    }

    const ClickAllTasks = (e) => {
        pageBody.replaceChildren();

        const divList = document.querySelectorAll("div");
        divList.forEach(element => element.classList.remove("active"));
        e.classList.add("active");


    }

    const clickList = (e) => {
        // Changes contents of .container to match contents of clicked Task
        pageBody.replaceChildren();

        const divList = document.querySelectorAll("div");
        divList.forEach(element => element.classList.remove("active"));
        e.classList.add("active");

        const list = listArray[e.id];
        const projectName = document.createElement("h2");
        projectName.className = "project-name";
        projectName.textContent = list.Name;
        pageBody.appendChild(projectName);

        const taskArray = list.getAllToDoItems();
        taskArray.forEach(task => {
            const taskContainer = document.createElement("div");
            taskContainer.className = "task-container";
            const checkBtn = document.createElement("button");
            checkBtn.className = "check-btn";

            const div = document.createElement("div");
            div.className = "task-wrapper";
            
            const title = document.createElement("h4");
            title.className = "title";
            const description = document.createElement("span");
            description.className = "description";
            const dueDate = document.createElement("span");
            dueDate.className = "dueDate";
            const priority = document.createElement("span");
            priority.className = "priority";
    
            title.textContent = task.title;
            description.textContent = task.description;

            pageBody.appendChild(taskContainer);
            taskContainer.appendChild(checkBtn);
            taskContainer.appendChild(div);
            div.appendChild(title);
            div.appendChild(description);
            div.appendChild(dueDate);
            div.appendChild(priority);
        });

    }

    const clickNewList = (e) => {
        //Show prompt for list title
    }


    // Generate Default List
    displayLists();

    //Attach listeners to static sidebar items
    const home = document.querySelector(".home");
    const today = document.querySelector(".today");
    const important = document.querySelector(".important");
    const allTasks = document.querySelector(".all-tasks");

    home.addEventListener("click", () => clickHome(home));
    today.addEventListener("click", () => clickToday(today));
    important.addEventListener("click", () => clickImportant(important));
    allTasks.addEventListener("click", () => ClickAllTasks(allTasks));

}



screenController();